# Generated by Django 4.1.1 on 2022-12-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.FloatField(verbose_name='Ёмкость')),
                ('amplitude', models.FloatField(verbose_name='Амплитуда')),
                ('duration', models.FloatField(verbose_name='Длительность')),
                ('resistance', models.FloatField(verbose_name='Сопротивление')),
                ('time', models.FloatField(verbose_name='Время')),
            ],
        ),
    ]
